<%
Const SiteName="友卓网"
Const SiteUrl=""
Const WebmasterEmail="admin@youapk.cn"
Const SiteDBPath="/include/youapk.db"
Const SiteDBPathBack="/include/dbbackup"
Const SiteCookie="youapk"
Const PublicTheme="/themes/public"
Const IndexTheme="/themes/default"
Const AdminTheme="/themes/admin"
Const IndexDes=""
Const IndexKey=""
Const AllowReg="0"
Const AllowComments="0"
Const ListComments="20"
Const ListApps="20"
Const AvatarPath="/upload/avatar"
Const AppPath="/upload/app"
Const AdPath="/upload/ads"
Const CountCode=""
Const SMTPServerAdd="smtp.163.com"
Const SMTPMail="laiguoxin@163.com"
Const SMTPUserName="laiguoxin@163.com"
Const SMTPUserPwd="19860815Lgx"
Const BanedWords="admin,administrator,管理员,操,干,操你妈,日你妈,干你妈逼,逼,阴茎,淫水,习近平,江泽民,毛泽东,爱液,射精,法轮功,胡锦涛,邓小平,达赖,傻逼,杂种,轮奸,强奸,滥交,群交,奶子,偷拍,睾丸,翻墙"
Const SiteStatus="0"
Const CopyRight="@ 2016 友卓网"
%>
